artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  # source_URL : https://github.com/entabby/Branching-tutorial/raw/master/winequality-data.zip
  source_URL : https://github.com/aniruddhachoudhury/Red-Wine-Quality/blob/master/winequality-red.csv
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion